// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/request/v1/hellorequest.proto

package hellorequest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name and how many greetings
// they want.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumGreetings         string   `protobuf:"bytes,2,opt,name=num_greetings,json=numGreetings,proto3" json:"num_greetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b24cbaae60b31a05, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetNumGreetings() string {
	if m != nil {
		return m.NumGreetings
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "protos.request.v1.HelloRequest")
}

func init() {
	proto.RegisterFile("protos/request/v1/hellorequest.proto", fileDescriptor_b24cbaae60b31a05)
}

var fileDescriptor_b24cbaae60b31a05 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2f, 0x33, 0xd4, 0xcf, 0x48,
	0xcd, 0xc9, 0xc9, 0x87, 0xf2, 0xf5, 0xc0, 0xd2, 0x42, 0x82, 0x10, 0x55, 0x7a, 0x30, 0xd1, 0x32,
	0x43, 0x25, 0x77, 0x2e, 0x1e, 0x0f, 0x90, 0xc2, 0x20, 0x88, 0x90, 0x90, 0x10, 0x17, 0x4b, 0x5e,
	0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0xa4, 0xcc, 0xc5, 0x9b,
	0x57, 0x9a, 0x1b, 0x9f, 0x5e, 0x94, 0x9a, 0x5a, 0x92, 0x99, 0x97, 0x5e, 0x2c, 0xc1, 0x04, 0x96,
	0xe4, 0xc9, 0x2b, 0xcd, 0x75, 0x87, 0x89, 0x39, 0x39, 0x46, 0xd9, 0xa7, 0x67, 0x96, 0x64, 0x94,
	0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x67, 0x27, 0x66, 0x96, 0xe4, 0x1b, 0xe9, 0x17, 0x27, 0xe6,
	0x16, 0xe4, 0xa4, 0x82, 0x6d, 0xd5, 0x4f, 0xcf, 0xd7, 0xc5, 0x70, 0xa4, 0x35, 0xb2, 0x23, 0x93,
	0xd8, 0xc0, 0xf2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x2b, 0xf5, 0x1f, 0xcd, 0x00,
	0x00, 0x00,
}
